### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by perguth** [ahdinosaur/uify#1]
``` sh
➜  Github npm install -g ahdinosaur/uify
...
➜  Github uify create my-super-cool-project
zsh: command not found: uify
```

What am I doing wrong?!

**Comment by ahdinosaur** [comment]
hey @pguth, you're not doing anything wrong, this actually doesn't work yet. :smile: 

it seems we're missing a `bin` property in the `package.json`, so `./bin/index.js` is not being linked to a global `uify` command.

**Comment by perguth** [comment]
That doesn't seem to solve it all (ahdinosaur/uify/pull/2). Running `node ./bin/index.js` should return some command line results right?

**Comment by ahdinosaur** [comment]
ah, add `--help`. need to make that happen with no args.

**Comment by perguth** [comment]
Switching the `else if (args.help)` for an `else` does the trick: ahdinosaur/uify/pull/3

**Comment by ahdinosaur** [comment]
hey thanks for the help. :smile: 

so the following should work in `0.1.2`:
- [x] `npm i -g uify`
- [x] `npm install -g ahdinosaur/uify`
- [x] `uify` returns usage for all
- [x] `uify --help` returns usage for all
- [x] `uify <command> --help` returns usage for `command`
- [x] `uify --version` returns version
- [x] `uify <subcommand> --version` returns version

feel free to keep filing issues and pull requests for whatever doesn't work.
